name: (chore) Daily Jobs

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  randomize-referrals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm i
      # TODO: Do stuff!
