name: Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/*.y*ml"

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v2.0.0
